"""GENERATED -- do not edit.

Produced by `python -m serpent._host._codegen` from the pinned `env.json`
(rs-soroban-env tag v28.0.2, upstream git blob sha
f9c50fc25c8f32cdc0a6d6f465d3b14143d446e3). Regenerate rather than hand-editing:

    uv run python -m serpent._host._codegen

`tests/unit/test_host_bindings.py::test_bindings_regeneration_is_byte_identical`
fails if this file drifts from a fresh run.

Imports only stdlib and `serpent._host._model` (see that module's docstring
for why: this file and `_model.py` must never form an import cycle with
`serpent._host/__init__.py`).
"""

from serpent._host._model import HostFn

HOST_FUNCTIONS: tuple[HostFn, ...] = (
    HostFn(
        name="log_from_linear_memory",
        module="x",
        export="_",
        arity=4,
        arg_names=("msg_pos", "msg_len", "vals_pos", "vals_len"),
        arg_types=("U32Val", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Emit a diagnostic event containing a message and sequence of `Val`s.",
    ),
    HostFn(
        name="obj_cmp",
        module="x",
        export="0",
        arity=2,
        arg_names=("a", "b"),
        arg_types=("Val", "Val"),
        ret_type="i64",
        min_protocol=None,
        max_protocol=None,
        docs="Compare two objects, or at least one object to a non-object, structurally. Returns -1 if a<b, 1 if a>b, or 0 if a==b.",
    ),
    HostFn(
        name="contract_event",
        module="x",
        export="1",
        arity=2,
        arg_names=("topics", "data"),
        arg_types=("VecObject", "Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Records a contract event. `topics` is expected to be a `SCVec`. Event size is limited by network configuration.",
    ),
    HostFn(
        name="get_ledger_version",
        module="x",
        export="2",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the protocol version of the current ledger as a u32.",
    ),
    HostFn(
        name="get_ledger_sequence",
        module="x",
        export="3",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the sequence number of the current ledger as a u32.",
    ),
    HostFn(
        name="get_ledger_timestamp",
        module="x",
        export="4",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="U64Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the timestamp number of the current ledger as a u64.",
    ),
    HostFn(
        name="fail_with_error",
        module="x",
        export="5",
        arity=1,
        arg_names=("error",),
        arg_types=("Error",),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Causes the currently executing contract to fail immediately with a provided error code, which must be of error-type `ScErrorType::Contract`. Does not actually return.",
    ),
    HostFn(
        name="get_ledger_network_id",
        module="x",
        export="6",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return the network id (sha256 hash of network passphrase) of the current ledger as `Bytes`. The value is always 32 bytes in length.",
    ),
    HostFn(
        name="get_current_contract_address",
        module="x",
        export="7",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="AddressObject",
        min_protocol=None,
        max_protocol=None,
        docs="Get the Address object for the current contract.",
    ),
    HostFn(
        name="get_max_live_until_ledger",
        module="x",
        export="8",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns the max ledger sequence that an entry can live to (inclusive).",
    ),
    HostFn(
        name="obj_from_u64",
        module="i",
        export="_",
        arity=1,
        arg_names=("v",),
        arg_types=("u64",),
        ret_type="U64Object",
        min_protocol=None,
        max_protocol=None,
        docs="Convert a `u64` to an object containing a `u64`.",
    ),
    HostFn(
        name="obj_to_u64",
        module="i",
        export="0",
        arity=1,
        arg_names=("obj",),
        arg_types=("U64Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Convert an object containing a `u64` to a `u64`.",
    ),
    HostFn(
        name="obj_from_i64",
        module="i",
        export="1",
        arity=1,
        arg_names=("v",),
        arg_types=("i64",),
        ret_type="I64Object",
        min_protocol=None,
        max_protocol=None,
        docs="Convert an `i64` to an object containing an `i64`.",
    ),
    HostFn(
        name="obj_to_i64",
        module="i",
        export="2",
        arity=1,
        arg_names=("obj",),
        arg_types=("I64Object",),
        ret_type="i64",
        min_protocol=None,
        max_protocol=None,
        docs="Convert an object containing an `i64` to an `i64`.",
    ),
    HostFn(
        name="obj_from_u128_pieces",
        module="i",
        export="3",
        arity=2,
        arg_names=("hi", "lo"),
        arg_types=("u64", "u64"),
        ret_type="U128Object",
        min_protocol=None,
        max_protocol=None,
        docs="Convert the high and low 64-bit words of a u128 to an object containing a u128.",
    ),
    HostFn(
        name="obj_to_u128_lo64",
        module="i",
        export="4",
        arity=1,
        arg_names=("obj",),
        arg_types=("U128Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the low 64 bits from an object containing a u128.",
    ),
    HostFn(
        name="obj_to_u128_hi64",
        module="i",
        export="5",
        arity=1,
        arg_names=("obj",),
        arg_types=("U128Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the high 64 bits from an object containing a u128.",
    ),
    HostFn(
        name="obj_from_i128_pieces",
        module="i",
        export="6",
        arity=2,
        arg_names=("hi", "lo"),
        arg_types=("i64", "u64"),
        ret_type="I128Object",
        min_protocol=None,
        max_protocol=None,
        docs="Convert the high and low 64-bit words of an i128 to an object containing an i128.",
    ),
    HostFn(
        name="obj_to_i128_lo64",
        module="i",
        export="7",
        arity=1,
        arg_names=("obj",),
        arg_types=("I128Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the low 64 bits from an object containing an i128.",
    ),
    HostFn(
        name="obj_to_i128_hi64",
        module="i",
        export="8",
        arity=1,
        arg_names=("obj",),
        arg_types=("I128Object",),
        ret_type="i64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the high 64 bits from an object containing an i128.",
    ),
    HostFn(
        name="obj_from_u256_pieces",
        module="i",
        export="9",
        arity=4,
        arg_names=("hi_hi", "hi_lo", "lo_hi", "lo_lo"),
        arg_types=("u64", "u64", "u64", "u64"),
        ret_type="U256Object",
        min_protocol=None,
        max_protocol=None,
        docs="Convert the four 64-bit words of a u256 (big-endian) to an object containing a u256.",
    ),
    HostFn(
        name="u256_val_from_be_bytes",
        module="i",
        export="a",
        arity=1,
        arg_names=("bytes",),
        arg_types=("BytesObject",),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Create a U256 `Val` from its representation as a byte array in big endian.",
    ),
    HostFn(
        name="u256_val_to_be_bytes",
        module="i",
        export="b",
        arity=1,
        arg_names=("val",),
        arg_types=("U256Val",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return the memory representation of this U256 `Val` as a byte array in big endian byte order.",
    ),
    HostFn(
        name="obj_to_u256_hi_hi",
        module="i",
        export="c",
        arity=1,
        arg_names=("obj",),
        arg_types=("U256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the highest 64-bits (bits 192-255) from an object containing a u256.",
    ),
    HostFn(
        name="obj_to_u256_hi_lo",
        module="i",
        export="d",
        arity=1,
        arg_names=("obj",),
        arg_types=("U256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract bits 128-191 from an object containing a u256.",
    ),
    HostFn(
        name="obj_to_u256_lo_hi",
        module="i",
        export="e",
        arity=1,
        arg_names=("obj",),
        arg_types=("U256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract bits 64-127 from an object containing a u256.",
    ),
    HostFn(
        name="obj_to_u256_lo_lo",
        module="i",
        export="f",
        arity=1,
        arg_names=("obj",),
        arg_types=("U256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the lowest 64-bits (bits 0-63) from an object containing a u256.",
    ),
    HostFn(
        name="obj_from_i256_pieces",
        module="i",
        export="g",
        arity=4,
        arg_names=("hi_hi", "hi_lo", "lo_hi", "lo_lo"),
        arg_types=("i64", "u64", "u64", "u64"),
        ret_type="I256Object",
        min_protocol=None,
        max_protocol=None,
        docs="Convert the four 64-bit words of an i256 (big-endian) to an object containing an i256.",
    ),
    HostFn(
        name="i256_val_from_be_bytes",
        module="i",
        export="h",
        arity=1,
        arg_names=("bytes",),
        arg_types=("BytesObject",),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Create a I256 `Val` from its representation as a byte array in big endian.",
    ),
    HostFn(
        name="i256_val_to_be_bytes",
        module="i",
        export="i",
        arity=1,
        arg_names=("val",),
        arg_types=("I256Val",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return the memory representation of this I256 `Val` as a byte array in big endian byte order.",
    ),
    HostFn(
        name="obj_to_i256_hi_hi",
        module="i",
        export="j",
        arity=1,
        arg_names=("obj",),
        arg_types=("I256Object",),
        ret_type="i64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the highest 64-bits (bits 192-255) from an object containing an i256.",
    ),
    HostFn(
        name="obj_to_i256_hi_lo",
        module="i",
        export="k",
        arity=1,
        arg_names=("obj",),
        arg_types=("I256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract bits 128-191 from an object containing an i256.",
    ),
    HostFn(
        name="obj_to_i256_lo_hi",
        module="i",
        export="l",
        arity=1,
        arg_names=("obj",),
        arg_types=("I256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract bits 64-127 from an object containing an i256.",
    ),
    HostFn(
        name="obj_to_i256_lo_lo",
        module="i",
        export="m",
        arity=1,
        arg_names=("obj",),
        arg_types=("I256Object",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Extract the lowest 64-bits (bits 0-63) from an object containing an i256.",
    ),
    HostFn(
        name="u256_add",
        module="i",
        export="n",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer addition. Computes `lhs + rhs`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="u256_sub",
        module="i",
        export="o",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer subtraction. Computes `lhs - rhs`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="u256_mul",
        module="i",
        export="p",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer multiplication. Computes `lhs * rhs`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="u256_div",
        module="i",
        export="q",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer division. Computes `lhs / rhs`, returning `ScError` if `rhs == 0` or overflow occurred. ",
    ),
    HostFn(
        name="u256_rem_euclid",
        module="i",
        export="r",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked Euclidean modulo. Computes `lhs % rhs`, returning `ScError` if `rhs == 0` or overflow occurred. ",
    ),
    HostFn(
        name="u256_pow",
        module="i",
        export="s",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U32Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked exponentiation. Computes `lhs.exp(rhs)`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="u256_shl",
        module="i",
        export="t",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U32Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked shift left. Computes `lhs << rhs`, returning `ScError` if `rhs` is larger than or equal to the number of bits in `lhs`.",
    ),
    HostFn(
        name="u256_shr",
        module="i",
        export="u",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U32Val"),
        ret_type="U256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked shift right. Computes `lhs >> rhs`, returning `ScError` if `rhs` is larger than or equal to the number of bits in `lhs`.",
    ),
    HostFn(
        name="i256_add",
        module="i",
        export="v",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer addition. Computes `lhs + rhs`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="i256_sub",
        module="i",
        export="w",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer subtraction. Computes `lhs - rhs`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="i256_mul",
        module="i",
        export="x",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer multiplication. Computes `lhs * rhs`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="i256_div",
        module="i",
        export="y",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked integer division. Computes `lhs / rhs`, returning `ScError` if `rhs == 0` or overflow occurred. ",
    ),
    HostFn(
        name="i256_rem_euclid",
        module="i",
        export="z",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked Euclidean modulo. Computes `lhs % rhs`, returning `ScError` if `rhs == 0` or overflow occurred. ",
    ),
    HostFn(
        name="i256_pow",
        module="i",
        export="A",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "U32Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked exponentiation. Computes `lhs.exp(rhs)`, returning `ScError` if overflow occurred. ",
    ),
    HostFn(
        name="i256_shl",
        module="i",
        export="B",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "U32Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked shift left. Computes `lhs << rhs`, returning `ScError` if `rhs` is larger than or equal to the number of bits in `lhs`.",
    ),
    HostFn(
        name="i256_shr",
        module="i",
        export="C",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "U32Val"),
        ret_type="I256Val",
        min_protocol=None,
        max_protocol=None,
        docs="Performs checked shift right. Computes `lhs >> rhs`, returning `ScError` if `rhs` is larger than or equal to the number of bits in `lhs`.",
    ),
    HostFn(
        name="timepoint_obj_from_u64",
        module="i",
        export="D",
        arity=1,
        arg_names=("v",),
        arg_types=("u64",),
        ret_type="TimepointObject",
        min_protocol=None,
        max_protocol=None,
        docs="Convert a `u64` to a `Timepoint` object.",
    ),
    HostFn(
        name="timepoint_obj_to_u64",
        module="i",
        export="E",
        arity=1,
        arg_names=("obj",),
        arg_types=("TimepointObject",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Convert a `Timepoint` object to a `u64`.",
    ),
    HostFn(
        name="duration_obj_from_u64",
        module="i",
        export="F",
        arity=1,
        arg_names=("v",),
        arg_types=("u64",),
        ret_type="DurationObject",
        min_protocol=None,
        max_protocol=None,
        docs="Convert a `u64` to a `Duration` object.",
    ),
    HostFn(
        name="duration_obj_to_u64",
        module="i",
        export="G",
        arity=1,
        arg_names=("obj",),
        arg_types=("DurationObject",),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Convert a `Duration` object a `u64`.",
    ),
    HostFn(
        name="u256_checked_add",
        module="i",
        export="H",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked addition. Computes `lhs + rhs`, returning `Void` if overflow occurred, otherwise returns `U256Val`.",
    ),
    HostFn(
        name="u256_checked_sub",
        module="i",
        export="I",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked subtraction. Computes `lhs - rhs`, returning `Void` if overflow occurred, otherwise returns `U256Val`.",
    ),
    HostFn(
        name="u256_checked_mul",
        module="i",
        export="J",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked multiplication. Computes `lhs * rhs`, returning `Void` if overflow occurred, otherwise returns `U256Val`.",
    ),
    HostFn(
        name="u256_checked_pow",
        module="i",
        export="K",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U32Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked exponentiation. Computes `lhs.exp(rhs)`, returning `Void` if overflow occurred, otherwise returns `U256Val`.",
    ),
    HostFn(
        name="i256_checked_add",
        module="i",
        export="L",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked addition. Computes `lhs + rhs`, returning `Void` if overflow occurred, otherwise returns `I256Val`.",
    ),
    HostFn(
        name="i256_checked_sub",
        module="i",
        export="M",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked subtraction. Computes `lhs - rhs`, returning `Void` if overflow occurred, otherwise returns `I256Val`.",
    ),
    HostFn(
        name="i256_checked_mul",
        module="i",
        export="N",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "I256Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked multiplication. Computes `lhs * rhs`, returning `Void` if overflow occurred, otherwise returns `I256Val`.",
    ),
    HostFn(
        name="i256_checked_pow",
        module="i",
        export="O",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("I256Val", "U32Val"),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs checked exponentiation. Computes `lhs.exp(rhs)`, returning `Void` if overflow occurred, otherwise returns `I256Val`.",
    ),
    HostFn(
        name="map_new",
        module="m",
        export="_",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="MapObject",
        min_protocol=None,
        max_protocol=None,
        docs="Create an empty new map.",
    ),
    HostFn(
        name="map_put",
        module="m",
        export="0",
        arity=3,
        arg_names=("m", "k", "v"),
        arg_types=("MapObject", "Val", "Val"),
        ret_type="MapObject",
        min_protocol=None,
        max_protocol=None,
        docs="Insert a key/value mapping into an existing map, and return the map object handle. If the map already has a mapping for the given key, the previous value is overwritten.",
    ),
    HostFn(
        name="map_get",
        module="m",
        export="1",
        arity=2,
        arg_names=("m", "k"),
        arg_types=("MapObject", "Val"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Get the value for a key from a map. Traps if key is not found.",
    ),
    HostFn(
        name="map_del",
        module="m",
        export="2",
        arity=2,
        arg_names=("m", "k"),
        arg_types=("MapObject", "Val"),
        ret_type="MapObject",
        min_protocol=None,
        max_protocol=None,
        docs="Remove a key/value mapping from a map if it exists, traps if doesn't.",
    ),
    HostFn(
        name="map_len",
        module="m",
        export="3",
        arity=1,
        arg_names=("m",),
        arg_types=("MapObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Get the size of a map.",
    ),
    HostFn(
        name="map_has",
        module="m",
        export="4",
        arity=2,
        arg_names=("m", "k"),
        arg_types=("MapObject", "Val"),
        ret_type="Bool",
        min_protocol=None,
        max_protocol=None,
        docs="Test for the presence of a key in a map. Returns Bool.",
    ),
    HostFn(
        name="map_key_by_pos",
        module="m",
        export="5",
        arity=2,
        arg_names=("m", "i"),
        arg_types=("MapObject", "U32Val"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Get the key from a map at position `i`. If `i` is an invalid position, return ScError.",
    ),
    HostFn(
        name="map_val_by_pos",
        module="m",
        export="6",
        arity=2,
        arg_names=("m", "i"),
        arg_types=("MapObject", "U32Val"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Get the value from a map at position `i`. If `i` is an invalid position, return ScError.",
    ),
    HostFn(
        name="map_keys",
        module="m",
        export="7",
        arity=1,
        arg_names=("m",),
        arg_types=("MapObject",),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return a new vector containing all the keys in a map. The new vector is ordered in the original map's key-sorted order.",
    ),
    HostFn(
        name="map_values",
        module="m",
        export="8",
        arity=1,
        arg_names=("m",),
        arg_types=("MapObject",),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return a new vector containing all the values in a map. The new vector is ordered in the original map's key-sorted order.",
    ),
    HostFn(
        name="map_new_from_linear_memory",
        module="m",
        export="9",
        arity=3,
        arg_names=("keys_pos", "vals_pos", "len"),
        arg_types=("U32Val", "U32Val", "U32Val"),
        ret_type="MapObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return a new map initialized from a pair of equal `len` length arrays, one for keys and one for values, specified by linear memory addresses. Key strings are specified as `len` 8 byte slices consisting of the 4 byte pointer and 4 byte length. Actual keys must be byte strings sorted in ascending order and be convertible to `Symbol` type. Values may be arbitrary `Val`s. Panics if any of the invariants above are violated.",
    ),
    HostFn(
        name="map_unpack_to_linear_memory",
        module="m",
        export="a",
        arity=4,
        arg_names=("map", "keys_pos", "vals_pos", "len"),
        arg_types=("MapObject", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Copy all value `Val`s from `map` to the linear memory array at `vals_pos` address. `len` must match the number of entries in `map`. Map keys must be of `Symbol` type and must match the key byte strings in the linear memory array at `keys_pos` address. Key strings are specified as 8 byte slices consisting of the 4 byte pointer and 4 byte length. Keys must be sorted in ascending order. Panics if any of the invariants above are violated.",
    ),
    HostFn(
        name="sparse_map_new_from_linear_memory",
        module="m",
        export="b",
        arity=3,
        arg_names=("keys_pos", "vals_pos", "len"),
        arg_types=("U32Val", "U32Val", "U32Val"),
        ret_type="MapObject",
        min_protocol=28,
        max_protocol=None,
        docs="Return a new map initialized from a pair of equal `len` length arrays, one for keys and one for values, specified by linear memory addresses. Key strings are specified as `len` 8 byte slices consisting of the 4 byte pointer and 4 byte length. Actual keys must be byte strings sorted in ascending order and be convertible to `Symbol` type. Values may be arbitrary `Val`s. Key-value pairs where the value is `Void` are not included into the final map. Panics if any of the invariants above are violated.",
    ),
    HostFn(
        name="sparse_map_unpack_to_linear_memory",
        module="m",
        export="c",
        arity=4,
        arg_names=("map", "keys_pos", "vals_pos", "len"),
        arg_types=("MapObject", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=28,
        max_protocol=None,
        docs="Fetch value `Val`s from `map` to the linear memory array at `vals_pos` address according to the key byte strings stored in linear memory at `keys_pos`. Key strings are specified as 8 byte slices consisting of the 4 byte pointer and 4 byte length. Keys must be sorted in ascending order. The map keys are expected to have `Symbol` type and its content bytes are matched to the input keys. If there is no matching map key, the corresponding value is set to `Void`. Panics if any of the invariants above are violated.",
    ),
    HostFn(
        name="vec_new",
        module="v",
        export="_",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Creates an empty new vector.",
    ),
    HostFn(
        name="vec_put",
        module="v",
        export="0",
        arity=3,
        arg_names=("v", "i", "x"),
        arg_types=("VecObject", "U32Val", "Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Update the value at index `i` in the vector. Return the new vector. Trap if the index is out of bounds.",
    ),
    HostFn(
        name="vec_get",
        module="v",
        export="1",
        arity=2,
        arg_names=("v", "i"),
        arg_types=("VecObject", "U32Val"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns the element at index `i` of the vector. Traps if the index is out of bound.",
    ),
    HostFn(
        name="vec_del",
        module="v",
        export="2",
        arity=2,
        arg_names=("v", "i"),
        arg_types=("VecObject", "U32Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Delete an element in a vector at index `i`, shifting all elements after it to the left. Return the new vector. Traps if the index is out of bound.",
    ),
    HostFn(
        name="vec_len",
        module="v",
        export="3",
        arity=1,
        arg_names=("v",),
        arg_types=("VecObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns length of the vector.",
    ),
    HostFn(
        name="vec_push_front",
        module="v",
        export="4",
        arity=2,
        arg_names=("v", "x"),
        arg_types=("VecObject", "Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Push a value to the front of a vector.",
    ),
    HostFn(
        name="vec_pop_front",
        module="v",
        export="5",
        arity=1,
        arg_names=("v",),
        arg_types=("VecObject",),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Removes the first element from the vector and returns the new vector. Traps if original vector is empty.",
    ),
    HostFn(
        name="vec_push_back",
        module="v",
        export="6",
        arity=2,
        arg_names=("v", "x"),
        arg_types=("VecObject", "Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Appends an element to the back of the vector.",
    ),
    HostFn(
        name="vec_pop_back",
        module="v",
        export="7",
        arity=1,
        arg_names=("v",),
        arg_types=("VecObject",),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Removes the last element from the vector and returns the new vector. Traps if original vector is empty.",
    ),
    HostFn(
        name="vec_front",
        module="v",
        export="8",
        arity=1,
        arg_names=("v",),
        arg_types=("VecObject",),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the first element in the vector. Traps if the vector is empty",
    ),
    HostFn(
        name="vec_back",
        module="v",
        export="9",
        arity=1,
        arg_names=("v",),
        arg_types=("VecObject",),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the last element in the vector. Traps if the vector is empty",
    ),
    HostFn(
        name="vec_insert",
        module="v",
        export="a",
        arity=3,
        arg_names=("v", "i", "x"),
        arg_types=("VecObject", "U32Val", "Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Inserts an element at index `i` within the vector, shifting all elements after it to the right. Traps if the index is out of bound",
    ),
    HostFn(
        name="vec_append",
        module="v",
        export="b",
        arity=2,
        arg_names=("v1", "v2"),
        arg_types=("VecObject", "VecObject"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Clone the vector `v1`, then moves all the elements of vector `v2` into it. Return the new vector. Traps if number of elements in the vector overflows a u32.",
    ),
    HostFn(
        name="vec_slice",
        module="v",
        export="c",
        arity=3,
        arg_names=("v", "start", "end"),
        arg_types=("VecObject", "U32Val", "U32Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Copy the elements from `start` index until `end` index, exclusive, in the vector and create a new vector from it. Return the new vector. Traps if the index is out of bound.",
    ),
    HostFn(
        name="vec_first_index_of",
        module="v",
        export="d",
        arity=2,
        arg_names=("v", "x"),
        arg_types=("VecObject", "Val"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Get the index of the first occurrence of a given element in the vector. Returns the u32 index of the value if it's there. Otherwise, it returns `Void`.",
    ),
    HostFn(
        name="vec_last_index_of",
        module="v",
        export="e",
        arity=2,
        arg_names=("v", "x"),
        arg_types=("VecObject", "Val"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Get the index of the last occurrence of a given element in the vector. Returns the u32 index of the value if it's there. Otherwise, it returns `Void`.",
    ),
    HostFn(
        name="vec_binary_search",
        module="v",
        export="f",
        arity=2,
        arg_names=("v", "x"),
        arg_types=("VecObject", "Val"),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Binary search a sorted vector for a given element. If it exists, the high 32 bits of the return value is 0x0000_0001 and the low 32 bits contain the u32 index of the element. If it does not exist, the high 32 bits of the return value is 0x0000_0000 and the low-32 bits contain the u32 index at which the element would need to be inserted into the vector to maintain sorted order.",
    ),
    HostFn(
        name="vec_new_from_linear_memory",
        module="v",
        export="g",
        arity=2,
        arg_names=("vals_pos", "len"),
        arg_types=("U32Val", "U32Val"),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return a new vec initialized from an input slice of Vals given by a linear-memory address and length in Vals.",
    ),
    HostFn(
        name="vec_unpack_to_linear_memory",
        module="v",
        export="h",
        arity=3,
        arg_names=("vec", "vals_pos", "len"),
        arg_types=("VecObject", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Copy the Vals of a vec into an array at a given linear-memory address and length in Vals.",
    ),
    HostFn(
        name="put_contract_data",
        module="l",
        export="_",
        arity=3,
        arg_names=("k", "v", "t"),
        arg_types=("Val", "Val", "StorageType"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="",
    ),
    HostFn(
        name="has_contract_data",
        module="l",
        export="0",
        arity=2,
        arg_names=("k", "t"),
        arg_types=("Val", "StorageType"),
        ret_type="Bool",
        min_protocol=None,
        max_protocol=None,
        docs="",
    ),
    HostFn(
        name="get_contract_data",
        module="l",
        export="1",
        arity=2,
        arg_names=("k", "t"),
        arg_types=("Val", "StorageType"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="",
    ),
    HostFn(
        name="del_contract_data",
        module="l",
        export="2",
        arity=2,
        arg_names=("k", "t"),
        arg_types=("Val", "StorageType"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="",
    ),
    HostFn(
        name="create_contract",
        module="l",
        export="3",
        arity=3,
        arg_names=("deployer", "wasm_hash", "salt"),
        arg_types=("AddressObject", "BytesObject", "BytesObject"),
        ret_type="AddressObject",
        min_protocol=None,
        max_protocol=None,
        docs="Creates the contract instance on behalf of `deployer`. `deployer` must authorize this call via Soroban auth framework, i.e. this calls `deployer.require_auth` with respective arguments. `wasm_hash` must be a hash of the contract code that has already been uploaded on this network. `salt` is used to create a unique contract id. Returns the address of the created contract.",
    ),
    HostFn(
        name="create_asset_contract",
        module="l",
        export="4",
        arity=1,
        arg_names=("serialized_asset",),
        arg_types=("BytesObject",),
        ret_type="AddressObject",
        min_protocol=None,
        max_protocol=None,
        docs="Creates the instance of Stellar Asset contract corresponding to the provided asset. `serialized_asset` is `stellar::Asset` XDR serialized to bytes format. Returns the address of the created contract.",
    ),
    HostFn(
        name="upload_wasm",
        module="l",
        export="5",
        arity=1,
        arg_names=("wasm",),
        arg_types=("BytesObject",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Uploads provided `wasm` bytecode to the network and returns its identifier (SHA-256 hash). No-op in case if the same Wasm object already exists.",
    ),
    HostFn(
        name="update_current_contract_wasm",
        module="l",
        export="6",
        arity=1,
        arg_names=("hash",),
        arg_types=("BytesObject",),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Replaces the executable of the current contract with the provided Wasm code identified by a hash. Wasm entry corresponding to the hash has to already be present in the ledger. The update happens only after the current contract invocation has successfully finished, so this can be safely called in the middle of a function.",
    ),
    HostFn(
        name="extend_contract_data_ttl",
        module="l",
        export="7",
        arity=4,
        arg_names=("k", "t", "threshold", "extend_to"),
        arg_types=("Val", "StorageType", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="If the entry's TTL is below `threshold` ledgers, extend `live_until_ledger_seq` such that TTL == `extend_to`, where TTL is defined as live_until_ledger_seq - current ledger. If attempting to extend the entry past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), and the entry is `Persistent`, its new `live_until_ledger_seq` will be clamped to the max; if the entry is `Temporary`, the function traps.",
    ),
    HostFn(
        name="extend_current_contract_instance_and_code_ttl",
        module="l",
        export="8",
        arity=2,
        arg_names=("threshold", "extend_to"),
        arg_types=("U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="If the TTL for the current contract instance and code (if applicable) is below `threshold` ledgers, extend `live_until_ledger_seq` such that TTL == `extend_to`, where TTL is defined as live_until_ledger_seq - current ledger. If attempting to extend past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), the new `live_until_ledger_seq` will be clamped to the max.",
    ),
    HostFn(
        name="extend_contract_instance_and_code_ttl",
        module="l",
        export="9",
        arity=3,
        arg_names=("contract", "threshold", "extend_to"),
        arg_types=("AddressObject", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="If the TTL for the provided contract instance and code (if applicable) is below `threshold` ledgers, extend `live_until_ledger_seq` such that TTL == `extend_to`, where TTL is defined as live_until_ledger_seq - current ledger. If attempting to extend past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), the new `live_until_ledger_seq` will be clamped to the max.",
    ),
    HostFn(
        name="get_contract_id",
        module="l",
        export="a",
        arity=2,
        arg_names=("deployer", "salt"),
        arg_types=("AddressObject", "BytesObject"),
        ret_type="AddressObject",
        min_protocol=None,
        max_protocol=None,
        docs="Get the id of a contract without creating it. `deployer` is address of the contract deployer. `salt` is used to create a unique contract id. Returns the address of the would-be contract.",
    ),
    HostFn(
        name="get_asset_contract_id",
        module="l",
        export="b",
        arity=1,
        arg_names=("serialized_asset",),
        arg_types=("BytesObject",),
        ret_type="AddressObject",
        min_protocol=None,
        max_protocol=None,
        docs="Get the id of the Stellar Asset contract corresponding to the provided asset without creating the instance. `serialized_asset` is `stellar::Asset` XDR serialized to bytes format. Returns the address of the would-be asset contract.",
    ),
    HostFn(
        name="extend_contract_instance_ttl",
        module="l",
        export="c",
        arity=3,
        arg_names=("contract", "threshold", "extend_to"),
        arg_types=("AddressObject", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=21,
        max_protocol=None,
        docs="If the TTL for the provided contract instance is below `threshold` ledgers, extend `live_until_ledger_seq` such that TTL == `extend_to`, where TTL is defined as live_until_ledger_seq - current ledger. If attempting to extend past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), the new `live_until_ledger_seq` will be clamped to the max.",
    ),
    HostFn(
        name="extend_contract_code_ttl",
        module="l",
        export="d",
        arity=3,
        arg_names=("contract", "threshold", "extend_to"),
        arg_types=("AddressObject", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=21,
        max_protocol=None,
        docs="If the TTL for the provided contract's code (if applicable) is below `threshold` ledgers, extend `live_until_ledger_seq` such that TTL == `extend_to`, where TTL is defined as live_until_ledger_seq - current ledger. If attempting to extend past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), the new `live_until_ledger_seq` will be clamped to the max.",
    ),
    HostFn(
        name="create_contract_with_constructor",
        module="l",
        export="e",
        arity=4,
        arg_names=("deployer", "wasm_hash", "salt", "constructor_args"),
        arg_types=("AddressObject", "BytesObject", "BytesObject", "VecObject"),
        ret_type="AddressObject",
        min_protocol=22,
        max_protocol=None,
        docs="Creates the contract instance on behalf of `deployer`. Created contract must be created from a Wasm that has a constructor. `deployer` must authorize this call via Soroban auth framework, i.e. this calls `deployer.require_auth` with respective arguments. `wasm_hash` must be a hash of the contract code that has already been uploaded on this network. `salt` is used to create a unique contract id. `constructor_args` are forwarded into created contract's constructor (`__constructor`) function. Returns the address of the created contract.",
    ),
    HostFn(
        name="extend_contract_data_ttl_v2",
        module="l",
        export="f",
        arity=5,
        arg_names=("k", "t", "extend_to", "min_extension", "max_extension"),
        arg_types=("Val", "StorageType", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=26,
        max_protocol=None,
        docs="Extend the contract data entry's TTL to be up to `extend_to` ledgers, where TTL is defined as `entry_live_until_ledger_seq - current_ledger_seq`. The TTL extension only actually happens if it is at least `min_extension`, otherwise this function is a no-op. The amount of extension ledgers will not exceed `max_extension` ledgers. If attempting to extend the entry past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), and the entry is `Persistent`, its new `live_until_ledger_seq` will be clamped to the max; if the entry is `Temporary`, the function traps.",
    ),
    HostFn(
        name="extend_contract_instance_and_code_ttl_v2",
        module="l",
        export="g",
        arity=5,
        arg_names=("contract", "extension_scope", "extend_to", "min_extension", "max_extension"),
        arg_types=("AddressObject", "ContractTtlExtension", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=26,
        max_protocol=None,
        docs="Extend the contract instance and/or corresponding code entry TTL to be up to `extend_to` ledgers, where TTL is defined as `entry_live_until_ledger_seq - current_ledger_seq`. `extension_scope` defines whether contract instance, code, or both will be extended. The TTL extension only actually happens if it is at least `min_extension`, otherwise this function is a no-op. The amount of extension ledgers will not exceed `max_extension` ledgers. If attempting to extend an entry past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), its new `live_until_ledger_seq` will be clamped to the max.",
    ),
    HostFn(
        name="create_executable_tag",
        module="l",
        export="h",
        arity=1,
        arg_names=("tag_string",),
        arg_types=("StringObject",),
        ret_type="ExecutableTagObject",
        min_protocol=28,
        max_protocol=None,
        docs="Creates a new `ExecutableTag` object holding the contents of the provided string. The tag acts as a key identifying an executable reference contract data entry. Executable reference entries may be used by other contracts to fetch their executable.",
    ),
    HostFn(
        name="create_external_ref_contract",
        module="l",
        export="i",
        arity=5,
        arg_names=("deployer", "executable_owner", "tag", "salt", "constructor_args"),
        arg_types=(
            "AddressObject",
            "AddressObject",
            "ExecutableTagObject",
            "BytesObject",
            "VecObject",
        ),
        ret_type="AddressObject",
        min_protocol=28,
        max_protocol=None,
        docs="Creates the contract instance on behalf of `deployer`. `deployer` must authorize this call via Soroban auth framework, i.e. this calls `deployer.require_auth` with respective arguments. Executable is read from the `executable_owner` contract storage entry keyed by `tag`. Currently the only supported external executable kind is hash of an existing Wasm. `salt` is used to create a unique contract id. `constructor_args` are forwarded into created contract's constructor (`__constructor`) function. Returns the address of the created contract.",
    ),
    HostFn(
        name="update_current_contract_executable_ref",
        module="l",
        export="j",
        arity=2,
        arg_names=("executable_owner", "tag"),
        arg_types=("AddressObject", "ExecutableTagObject"),
        ret_type="Void",
        min_protocol=28,
        max_protocol=None,
        docs="Replaces the executable of the current contract with the provided executable reference. Executable is read from the `executable_owner` contract storage entry keyed by `tag`. Currently the only supported external executable kind is hash of an existing Wasm. The update happens only after the current contract invocation has successfully finished, so this can be safely called in the middle of a function.",
    ),
    HostFn(
        name="call",
        module="d",
        export="_",
        arity=3,
        arg_names=("contract", "func", "args"),
        arg_types=("AddressObject", "Symbol", "VecObject"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Calls a function in another contract with arguments contained in vector `args`. If the call is successful, returns the result of the called function. Traps otherwise.",
    ),
    HostFn(
        name="try_call",
        module="d",
        export="0",
        arity=3,
        arg_names=("contract", "func", "args"),
        arg_types=("AddressObject", "Symbol", "VecObject"),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Calls a function in another contract with arguments contained in vector `args`, returning either the result of the called function or an `Error` if the called function failed. The returned error is either a custom `ContractError` that the called contract returns explicitly, or an error with type `Context` and code `InvalidAction` in case of any other error in the called contract (such as a host function failure that caused a trap). `try_call` might trap in a few scenarios where the error can't be meaningfully recovered from, such as running out of budget.",
    ),
    HostFn(
        name="serialize_to_bytes",
        module="b",
        export="_",
        arity=1,
        arg_names=("v",),
        arg_types=("Val",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Serializes an (SC)Val into XDR opaque `Bytes` object.",
    ),
    HostFn(
        name="deserialize_from_bytes",
        module="b",
        export="0",
        arity=1,
        arg_names=("b",),
        arg_types=("BytesObject",),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="Deserialize a `Bytes` object to get back the (SC)Val.",
    ),
    HostFn(
        name="bytes_copy_to_linear_memory",
        module="b",
        export="1",
        arity=4,
        arg_names=("b", "b_pos", "lm_pos", "len"),
        arg_types=("BytesObject", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Copies a slice of bytes from a `Bytes` object specified at offset `b_pos` with length `len` into the linear memory at position `lm_pos`. Traps if either the `Bytes` object or the linear memory doesn't have enough bytes.",
    ),
    HostFn(
        name="bytes_copy_from_linear_memory",
        module="b",
        export="2",
        arity=4,
        arg_names=("b", "b_pos", "lm_pos", "len"),
        arg_types=("BytesObject", "U32Val", "U32Val", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Copies a segment of the linear memory specified at position `lm_pos` with length `len`, into a `Bytes` object at offset `b_pos`. The `Bytes` object may grow in size to accommodate the new bytes. Traps if the linear memory doesn't have enough bytes.",
    ),
    HostFn(
        name="bytes_new_from_linear_memory",
        module="b",
        export="3",
        arity=2,
        arg_names=("lm_pos", "len"),
        arg_types=("U32Val", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Constructs a new `Bytes` object initialized with bytes copied from a linear memory slice specified at position `lm_pos` with length `len`.",
    ),
    HostFn(
        name="bytes_new",
        module="b",
        export="4",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Create an empty new `Bytes` object.",
    ),
    HostFn(
        name="bytes_put",
        module="b",
        export="5",
        arity=3,
        arg_names=("b", "i", "u"),
        arg_types=("BytesObject", "U32Val", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Update the value at index `i` in the `Bytes` object. Return the new `Bytes`. Trap if the index is out of bounds.",
    ),
    HostFn(
        name="bytes_get",
        module="b",
        export="6",
        arity=2,
        arg_names=("b", "i"),
        arg_types=("BytesObject", "U32Val"),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns the element at index `i` of the `Bytes` object. Traps if the index is out of bound.",
    ),
    HostFn(
        name="bytes_del",
        module="b",
        export="7",
        arity=2,
        arg_names=("b", "i"),
        arg_types=("BytesObject", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Delete an element in a `Bytes` object at index `i`, shifting all elements after it to the left. Return the new `Bytes`. Traps if the index is out of bound.",
    ),
    HostFn(
        name="bytes_len",
        module="b",
        export="8",
        arity=1,
        arg_names=("b",),
        arg_types=("BytesObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns length of the `Bytes` object.",
    ),
    HostFn(
        name="bytes_push",
        module="b",
        export="9",
        arity=2,
        arg_names=("b", "u"),
        arg_types=("BytesObject", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Appends an element to the back of the `Bytes` object.",
    ),
    HostFn(
        name="bytes_pop",
        module="b",
        export="a",
        arity=1,
        arg_names=("b",),
        arg_types=("BytesObject",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Removes the last element from the `Bytes` object and returns the new `Bytes`. Traps if original `Bytes` is empty.",
    ),
    HostFn(
        name="bytes_front",
        module="b",
        export="b",
        arity=1,
        arg_names=("b",),
        arg_types=("BytesObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the first element in the `Bytes` object. Traps if the `Bytes` is empty",
    ),
    HostFn(
        name="bytes_back",
        module="b",
        export="c",
        arity=1,
        arg_names=("b",),
        arg_types=("BytesObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the last element in the `Bytes` object. Traps if the `Bytes` is empty",
    ),
    HostFn(
        name="bytes_insert",
        module="b",
        export="d",
        arity=3,
        arg_names=("b", "i", "u"),
        arg_types=("BytesObject", "U32Val", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Inserts an element at index `i` within the `Bytes` object, shifting all elements after it to the right. Traps if the index is out of bound",
    ),
    HostFn(
        name="bytes_append",
        module="b",
        export="e",
        arity=2,
        arg_names=("b1", "b2"),
        arg_types=("BytesObject", "BytesObject"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Clone the `Bytes` object `b1`, then moves all the elements of `Bytes` object `b2` into it. Return the new `Bytes`. Traps if its length overflows a u32.",
    ),
    HostFn(
        name="bytes_slice",
        module="b",
        export="f",
        arity=3,
        arg_names=("b", "start", "end"),
        arg_types=("BytesObject", "U32Val", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Copies the elements from `start` index until `end` index, exclusive, in the `Bytes` object and creates a new `Bytes` from it. Returns the new `Bytes`. Traps if the index is out of bound.",
    ),
    HostFn(
        name="string_copy_to_linear_memory",
        module="b",
        export="g",
        arity=4,
        arg_names=("s", "s_pos", "lm_pos", "len"),
        arg_types=("StringObject", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Copies a slice of bytes from a `String` object specified at offset `s_pos` with length `len` into the linear memory at position `lm_pos`. Traps if either the `String` object or the linear memory doesn't have enough bytes.",
    ),
    HostFn(
        name="symbol_copy_to_linear_memory",
        module="b",
        export="h",
        arity=4,
        arg_names=("s", "s_pos", "lm_pos", "len"),
        arg_types=("SymbolObject", "U32Val", "U32Val", "U32Val"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Copies a slice of bytes from a `Symbol` object specified at offset `s_pos` with length `len` into the linear memory at position `lm_pos`. Traps if either the `String` object or the linear memory doesn't have enough bytes.",
    ),
    HostFn(
        name="string_new_from_linear_memory",
        module="b",
        export="i",
        arity=2,
        arg_names=("lm_pos", "len"),
        arg_types=("U32Val", "U32Val"),
        ret_type="StringObject",
        min_protocol=None,
        max_protocol=None,
        docs="Constructs a new `String` object initialized with bytes copied from a linear memory slice specified at position `lm_pos` with length `len`.",
    ),
    HostFn(
        name="symbol_new_from_linear_memory",
        module="b",
        export="j",
        arity=2,
        arg_names=("lm_pos", "len"),
        arg_types=("U32Val", "U32Val"),
        ret_type="SymbolObject",
        min_protocol=None,
        max_protocol=None,
        docs="Constructs a new `Symbol` object initialized with bytes copied from a linear memory slice specified at position `lm_pos` with length `len`.",
    ),
    HostFn(
        name="string_len",
        module="b",
        export="k",
        arity=1,
        arg_names=("s",),
        arg_types=("StringObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns length of the `String` object.",
    ),
    HostFn(
        name="symbol_len",
        module="b",
        export="l",
        arity=1,
        arg_names=("s",),
        arg_types=("SymbolObject",),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Returns length of the `Symbol` object.",
    ),
    HostFn(
        name="symbol_index_in_linear_memory",
        module="b",
        export="m",
        arity=3,
        arg_names=("sym", "slices_pos", "len"),
        arg_types=("Symbol", "U32Val", "U32Val"),
        ret_type="U32Val",
        min_protocol=None,
        max_protocol=None,
        docs="Return the index of a Symbol in an array of linear-memory byte-slices, or trap if not found.",
    ),
    HostFn(
        name="string_to_bytes",
        module="b",
        export="n",
        arity=1,
        arg_names=("str",),
        arg_types=("StringObject",),
        ret_type="BytesObject",
        min_protocol=23,
        max_protocol=None,
        docs="Converts the provided string to bytes with exactly the same contents.",
    ),
    HostFn(
        name="bytes_to_string",
        module="b",
        export="o",
        arity=1,
        arg_names=("bytes",),
        arg_types=("BytesObject",),
        ret_type="StringObject",
        min_protocol=23,
        max_protocol=None,
        docs="Converts the provided bytes array to string with exactly the same contents. No encoding checks are performed and thus the output string's encoding should be interpreted by the consumer of the string.",
    ),
    HostFn(
        name="compute_hash_sha256",
        module="c",
        export="_",
        arity=1,
        arg_names=("x",),
        arg_types=("BytesObject",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="",
    ),
    HostFn(
        name="verify_sig_ed25519",
        module="c",
        export="0",
        arity=3,
        arg_names=("k", "x", "s"),
        arg_types=("BytesObject", "BytesObject", "BytesObject"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="",
    ),
    HostFn(
        name="compute_hash_keccak256",
        module="c",
        export="1",
        arity=1,
        arg_names=("x",),
        arg_types=("BytesObject",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Returns the keccak256 hash of given input bytes.",
    ),
    HostFn(
        name="recover_key_ecdsa_secp256k1",
        module="c",
        export="2",
        arity=3,
        arg_names=("msg_digest", "signature", "recovery_id"),
        arg_types=("BytesObject", "BytesObject", "U32Val"),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Recovers the SEC-1-encoded ECDSA secp256k1 public key that produced a given 64-byte `signature` over a given 32-byte `msg_digest` for a given `recovery_id` byte. Warning: The `msg_digest` must be produced by a secure cryptographic hash function on the message, otherwise the attacker can potentially forge signatures.  The `signature` is the ECDSA signature `(r, s)` serialized as fixed-size big endian scalar values, both `r`, `s` must be non-zero and `s` must be in the lower range. Returns a `BytesObject` containing 65-bytes representing SEC-1 encoded point in uncompressed format. The `recovery_id` is an integer value `0`, `1`, `2`, or `3`, the low bit (0/1) indicates the parity of the y-coordinate of the `public_key` (even/odd) and the high bit (3/4) indicate if the `r` (x-coordinate of `k x G`) has overflown during its computation.",
    ),
    HostFn(
        name="verify_sig_ecdsa_secp256r1",
        module="c",
        export="3",
        arity=3,
        arg_names=("public_key", "msg_digest", "signature"),
        arg_types=("BytesObject", "BytesObject", "BytesObject"),
        ret_type="Void",
        min_protocol=21,
        max_protocol=None,
        docs="Verifies the `signature` using an ECDSA secp256r1 `public_key` on a 32-byte `msg_digest`. Warning: The `msg_digest` must be produced by a secure cryptographic hash function on the message, otherwise the attacker can potentially forge signatures. The `public_key` is expected to be 65 bytes in length, representing a SEC-1 encoded point in uncompressed format. The `signature` is the ECDSA signature `(r, s)` serialized as fixed-size big endian scalar values, both `r`, `s` must be non-zero and `s` must be in the lower range. ",
    ),
    HostFn(
        name="bls12_381_check_g1_is_in_subgroup",
        module="c",
        export="4",
        arity=1,
        arg_names=("point",),
        arg_types=("BytesObject",),
        ret_type="Bool",
        min_protocol=22,
        max_protocol=None,
        docs="Checks if the input G1 point is in the correct subgroup. This function will error if `point` is not on the curve",
    ),
    HostFn(
        name="bls12_381_g1_add",
        module="c",
        export="5",
        arity=2,
        arg_names=("point1", "point2"),
        arg_types=("BytesObject", "BytesObject"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Adds two BLS12-381 G1 points given in bytes format and returns the resulting G1 point in bytes format. G1 serialization format: `concat(be_bytes(X), be_bytes(Y))` and the most significant three bits of X encodes flags, i.e.  bits(X) = [compression_flag, infinity_flag, sort_flag, bit_3, .. bit_383]. This function does NOT perform subgroup check on the inputs.",
    ),
    HostFn(
        name="bls12_381_g1_mul",
        module="c",
        export="6",
        arity=2,
        arg_names=("point", "scalar"),
        arg_types=("BytesObject", "U256Val"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Multiplies a BLS12-381 G1 point by a scalar (Fr), and returns the resulting G1 point in bytes format.",
    ),
    HostFn(
        name="bls12_381_g1_msm",
        module="c",
        export="7",
        arity=2,
        arg_names=("vp", "vs"),
        arg_types=("VecObject", "VecObject"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Performs multi-scalar-multiplication (inner product) on a vector of BLS12-381 G1 points (`Vec<BytesObject>`) by a vector of scalars (`Vec<U256Val>`), and returns the resulting G1 point in bytes format.",
    ),
    HostFn(
        name="bls12_381_map_fp_to_g1",
        module="c",
        export="8",
        arity=1,
        arg_names=("fp",),
        arg_types=("BytesObject",),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Maps a BLS12-381 field element (Fp) to G1 point. The input is a BytesObject containing Fp serialized in big-endian order",
    ),
    HostFn(
        name="bls12_381_hash_to_g1",
        module="c",
        export="9",
        arity=2,
        arg_names=("msg", "dst"),
        arg_types=("BytesObject", "BytesObject"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Hashes a message to a BLS12-381 G1 point, with implementation following the specification in [Hashing to Elliptic Curves](https://datatracker.ietf.org/doc/html/rfc9380) (ciphersuite 'BLS12381G1_XMD:SHA-256_SSWU_RO_'). `dst` is the domain separation tag that will be concatenated with the `msg` during hashing, it is intended to keep hashing inputs of different applications separate. It is required `0 < len(dst_bytes) < 256`. DST **must** be chosen with care to avoid compromising the application's security properties. Refer to section 3.1 in the RFC on requirements of DST.",
    ),
    HostFn(
        name="bls12_381_check_g2_is_in_subgroup",
        module="c",
        export="a",
        arity=1,
        arg_names=("point",),
        arg_types=("BytesObject",),
        ret_type="Bool",
        min_protocol=22,
        max_protocol=None,
        docs="Checks if the input G2 point is in the correct subgroup. This function will error if `point` is not on the curve",
    ),
    HostFn(
        name="bls12_381_g2_add",
        module="c",
        export="b",
        arity=2,
        arg_names=("point1", "point2"),
        arg_types=("BytesObject", "BytesObject"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Adds two BLS12-381 G2 points given in bytes format and returns the resulting G2 point in bytes format. G2 serialization format: concat(be_bytes(X_c1), be_bytes(X_c0), be_bytes(Y_c1), be_bytes(Y_c0)), and the most significant three bits of X_c1 are flags i.e. bits(X_c1) = [compression_flag, infinity_flag, sort_flag, bit_3, .. bit_383]. This function does NOT perform subgroup check on the inputs.",
    ),
    HostFn(
        name="bls12_381_g2_mul",
        module="c",
        export="c",
        arity=2,
        arg_names=("point", "scalar"),
        arg_types=("BytesObject", "U256Val"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Multiplies a BLS12-381 G2 point by a scalar (Fr), and returns the resulting G2 point in bytes format.",
    ),
    HostFn(
        name="bls12_381_g2_msm",
        module="c",
        export="d",
        arity=2,
        arg_names=("vp", "vs"),
        arg_types=("VecObject", "VecObject"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Performs multi-scalar-multiplication (inner product) on a vector of BLS12-381 G2 points (`Vec<BytesObject>`) by a vector of scalars (`Vec<U256Val>`) , and returns the resulting G2 point in bytes format.",
    ),
    HostFn(
        name="bls12_381_map_fp2_to_g2",
        module="c",
        export="e",
        arity=1,
        arg_names=("fp2",),
        arg_types=("BytesObject",),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Maps a BLS12-381 quadratic extension field element (Fp2) to G2 point. Fp2 serialization format: concat(be_bytes(c1), be_bytes(c0))",
    ),
    HostFn(
        name="bls12_381_hash_to_g2",
        module="c",
        export="f",
        arity=2,
        arg_names=("msg", "dst"),
        arg_types=("BytesObject", "BytesObject"),
        ret_type="BytesObject",
        min_protocol=22,
        max_protocol=None,
        docs="Hashes a message to a BLS12-381 G2 point, with implementation following the specification in [Hashing to Elliptic Curves](https://datatracker.ietf.org/doc/html/rfc9380) (ciphersuite 'BLS12381G2_XMD:SHA-256_SSWU_RO_'). `dst` is the domain separation tag that will be concatenated with the `msg` during hashing, it is intended to keep hashing inputs of different applications separate. It is required `0 < len(dst_bytes) < 256`. DST **must** be chosen with care to avoid compromising the application's security properties. Refer to section 3.1 in the RFC on requirements of DST.",
    ),
    HostFn(
        name="bls12_381_multi_pairing_check",
        module="c",
        export="g",
        arity=2,
        arg_names=("vp1", "vp2"),
        arg_types=("VecObject", "VecObject"),
        ret_type="Bool",
        min_protocol=22,
        max_protocol=None,
        docs="performs pairing operation on a vector of `G1` (`Vec<BytesObject>`)  and a vector of `G2` points (`Vec<BytesObject>`) , return true if the result equals `1_fp12`",
    ),
    HostFn(
        name="bls12_381_fr_add",
        module="c",
        export="h",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=22,
        max_protocol=None,
        docs="performs addition `(lhs + rhs) mod r` between two BLS12-381 scalar elements (Fr), where r is the subgroup order",
    ),
    HostFn(
        name="bls12_381_fr_sub",
        module="c",
        export="i",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=22,
        max_protocol=None,
        docs="performs subtraction `(lhs - rhs) mod r` between two BLS12-381 scalar elements (Fr), where r is the subgroup order",
    ),
    HostFn(
        name="bls12_381_fr_mul",
        module="c",
        export="j",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=22,
        max_protocol=None,
        docs="performs multiplication `(lhs * rhs) mod r` between two BLS12-381 scalar elements (Fr), where r is the subgroup order",
    ),
    HostFn(
        name="bls12_381_fr_pow",
        module="c",
        export="k",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U64Val"),
        ret_type="U256Val",
        min_protocol=22,
        max_protocol=None,
        docs="performs exponentiation of a BLS12-381 scalar element (Fr) with a u64 exponent i.e. `lhs.exp(rhs) mod r`, where r is the subgroup order",
    ),
    HostFn(
        name="bls12_381_fr_inv",
        module="c",
        export="l",
        arity=1,
        arg_names=("lhs",),
        arg_types=("U256Val",),
        ret_type="U256Val",
        min_protocol=22,
        max_protocol=None,
        docs="performs inversion of a BLS12-381 scalar element (Fr) modulo r (the subgroup order)",
    ),
    HostFn(
        name="bn254_g1_add",
        module="c",
        export="m",
        arity=2,
        arg_names=("point1", "point2"),
        arg_types=("BytesObject", "BytesObject"),
        ret_type="BytesObject",
        min_protocol=25,
        max_protocol=None,
        docs="Adds two BN254 G1 points. G1 encoding: 64-byte uncompressed format: be_bytes(X)||be_bytes(Y), where X and Y are 32-byte big-endian Fp field elements. The two flag bits (0x80 and 0x40) of the first byte must be unset -- infinity is represented as 64 zero bytes. Points must be on curve with no subgroup check needed (always in subgroup)",
    ),
    HostFn(
        name="bn254_g1_mul",
        module="c",
        export="n",
        arity=2,
        arg_names=("point", "scalar"),
        arg_types=("BytesObject", "U256Val"),
        ret_type="BytesObject",
        min_protocol=25,
        max_protocol=None,
        docs="Multiplies a BN254 G1 point by a scalar from the scalar field Fr. The point uses the same 64-byte encoding as bn254_g1_add. The scalar is a U256Val representing a 256-bit integer that is reduced modulo the Fr field order.",
    ),
    HostFn(
        name="bn254_multi_pairing_check",
        module="c",
        export="o",
        arity=2,
        arg_names=("vp1", "vp2"),
        arg_types=("VecObject", "VecObject"),
        ret_type="Bool",
        min_protocol=25,
        max_protocol=None,
        docs="Performs BN254 multi-pairing check over equal-length non-empty vectors of G1 and G2 points. Returns true iff the product of pairings e(G1[0],G2[0])*...*e(G1[n-1],G2[n-1]) equals 1 in Fq12. G1 encoding: 64 bytes as in bn254_g1_add. G2 encoding: 128-byte uncompressed format: be_bytes(X)||be_bytes(Y), where X and Y are Fp2 elements (64 bytes each). Fp2 element encoding: be_bytes(c1)||be_bytes(c0) where c0 is the real part and c1 is the imaginary part (each 32-byte big-endian Fp). The two flag bits (0x80 and 0x40) of the first byte must be unset -- G2 infinity is 128 zero bytes. G2 points must be on curve AND in the correct subgroup.",
    ),
    HostFn(
        name="poseidon_permutation",
        module="c",
        export="p",
        arity=8,
        arg_names=("input", "field", "t", "d", "rounds_f", "rounds_p", "mds", "round_constants"),
        arg_types=(
            "VecObject",
            "Symbol",
            "U32Val",
            "U32Val",
            "U32Val",
            "U32Val",
            "VecObject",
            "VecObject",
        ),
        ret_type="VecObject",
        min_protocol=25,
        max_protocol=None,
        docs="Performs Poseidon permutation on input vector. input: vector of field elements (length t). field: 'BLS12_381' or 'BN254'. t: state size. d: S-box degree (5 for BLS12_381/BN254). rounds_f: number of full rounds (must be even). rounds_p: number of partial rounds. mds: t-by-t MDS matrix as Vec<Vec<Scalar>>. round_constants: (rounds_f+rounds_p)-by-t round constants matrix as Vec<Vec<Scalar>>. Returns output vector after permutation.",
    ),
    HostFn(
        name="poseidon2_permutation",
        module="c",
        export="q",
        arity=8,
        arg_names=(
            "input",
            "field",
            "t",
            "d",
            "rounds_f",
            "rounds_p",
            "mat_internal_diag_m_1",
            "round_constants",
        ),
        arg_types=(
            "VecObject",
            "Symbol",
            "U32Val",
            "U32Val",
            "U32Val",
            "U32Val",
            "VecObject",
            "VecObject",
        ),
        ret_type="VecObject",
        min_protocol=25,
        max_protocol=None,
        docs="Performs Poseidon2 permutation on input vector. input: vector of field elements (length t). field: 'BLS12_381' or 'BN254'. t: state size. d: S-box degree (5 for BLS12_381/BN254). rounds_f: number of full rounds (must be even). rounds_p: number of partial rounds. mat_internal_diag_m_1: internal matrix diagonal minus 1 as Vec<Scalar> (length t). round_constants: (rounds_f+rounds_p)-by-t round constants matrix as Vec<Vec<Scalar>>. Returns output vector after permutation.",
    ),
    HostFn(
        name="bn254_g1_msm",
        module="c",
        export="r",
        arity=2,
        arg_names=("vp", "vs"),
        arg_types=("VecObject", "VecObject"),
        ret_type="BytesObject",
        min_protocol=26,
        max_protocol=None,
        docs="Performs multi-scalar-multiplication (inner product) on a vector of BN254 G1 points (`Vec<BytesObject>`) by a vector of scalars (`Vec<U256Val>`), and returns the resulting G1 point in 64-byte uncompressed format.",
    ),
    HostFn(
        name="bn254_fr_add",
        module="c",
        export="s",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs addition `(lhs + rhs) mod r` between two BN254 scalar elements (Fr), where r is the subgroup order",
    ),
    HostFn(
        name="bn254_fr_sub",
        module="c",
        export="t",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs subtraction `(lhs - rhs) mod r` between two BN254 scalar elements (Fr), where r is the subgroup order",
    ),
    HostFn(
        name="bn254_fr_mul",
        module="c",
        export="u",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U256Val"),
        ret_type="U256Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs multiplication `(lhs * rhs) mod r` between two BN254 scalar elements (Fr), where r is the subgroup order",
    ),
    HostFn(
        name="bn254_fr_pow",
        module="c",
        export="v",
        arity=2,
        arg_names=("lhs", "rhs"),
        arg_types=("U256Val", "U64Val"),
        ret_type="U256Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs exponentiation of a BN254 scalar element (Fr) with a u64 exponent i.e. `lhs.exp(rhs) mod r`, where r is the subgroup order",
    ),
    HostFn(
        name="bn254_fr_inv",
        module="c",
        export="w",
        arity=1,
        arg_names=("lhs",),
        arg_types=("U256Val",),
        ret_type="U256Val",
        min_protocol=26,
        max_protocol=None,
        docs="Performs inversion of a BN254 scalar element (Fr) modulo r (the subgroup order)",
    ),
    HostFn(
        name="bls12_381_g1_is_on_curve",
        module="c",
        export="x",
        arity=1,
        arg_names=("point",),
        arg_types=("BytesObject",),
        ret_type="Bool",
        min_protocol=26,
        max_protocol=None,
        docs="Checks if a BLS12-381 G1 point is on the curve (does not check subgroup membership). Returns true if the point is on the curve, false otherwise.",
    ),
    HostFn(
        name="bls12_381_g2_is_on_curve",
        module="c",
        export="y",
        arity=1,
        arg_names=("point",),
        arg_types=("BytesObject",),
        ret_type="Bool",
        min_protocol=26,
        max_protocol=None,
        docs="Checks if a BLS12-381 G2 point is on the curve (does not check subgroup membership). Returns true if the point is on the curve, false otherwise.",
    ),
    HostFn(
        name="bn254_g1_is_on_curve",
        module="c",
        export="z",
        arity=1,
        arg_names=("point",),
        arg_types=("BytesObject",),
        ret_type="Bool",
        min_protocol=26,
        max_protocol=None,
        docs="Checks if a BN254 G1 point is on the curve. Returns true if the point is on the curve, false otherwise.",
    ),
    HostFn(
        name="require_auth_for_args",
        module="a",
        export="_",
        arity=2,
        arg_names=("address", "args"),
        arg_types=("AddressObject", "VecObject"),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Checks if the address has authorized the invocation of the current contract function with the provided arguments. Traps if the invocation hasn't been authorized.",
    ),
    HostFn(
        name="require_auth",
        module="a",
        export="0",
        arity=1,
        arg_names=("address",),
        arg_types=("AddressObject",),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Checks if the address has authorized the invocation of the current contract function with all the arguments of the invocation. Traps if the invocation hasn't been authorized.",
    ),
    HostFn(
        name="strkey_to_address",
        module="a",
        export="1",
        arity=1,
        arg_names=("strkey",),
        arg_types=("Val",),
        ret_type="AddressObject",
        min_protocol=None,
        max_protocol=None,
        docs="Converts a provided Stellar strkey address of an account or a contract ('G...' or 'C...' respectively) to an address object. `strkey` can be either `BytesObject` or `StringObject` (the contents should represent the `G.../C...` string in both cases). Any other valid or invalid strkey (e.g. 'S...') will trigger an error. Prefer directly using the Address objects whenever possible. This is only useful in the context of custom messaging protocols (e.g. cross-chain).",
    ),
    HostFn(
        name="address_to_strkey",
        module="a",
        export="2",
        arity=1,
        arg_names=("address",),
        arg_types=("AddressObject",),
        ret_type="StringObject",
        min_protocol=None,
        max_protocol=None,
        docs="Converts a provided address to Stellar strkey format ('G...' for account or 'C...' for contract). Prefer directly using the Address objects whenever possible. This is only useful in the context of custom messaging protocols (e.g. cross-chain).",
    ),
    HostFn(
        name="authorize_as_curr_contract",
        module="a",
        export="3",
        arity=1,
        arg_names=("auth_entires",),
        arg_types=("VecObject",),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Authorizes sub-contract calls for the next contract call on behalf of the current contract. Every entry in the argument vector corresponds to `InvokerContractAuthEntry` contract type that authorizes a tree of `require_auth` calls on behalf of the current contract. The entries must not contain any authorizations for the direct contract call, i.e. if current contract needs to call contract function F1 that calls function F2 both of which require auth, only F2 should be present in `auth_entries`.",
    ),
    HostFn(
        name="get_address_from_muxed_address",
        module="a",
        export="4",
        arity=1,
        arg_names=("muxed_address",),
        arg_types=("MuxedAddressObject",),
        ret_type="AddressObject",
        min_protocol=23,
        max_protocol=None,
        docs="Returns the address corresponding to the provided MuxedAddressObject as a new AddressObject. Note, that MuxedAddressObject consists of the address and multiplexing id, so this conversion just strips the multiplexing id from the input muxed address.",
    ),
    HostFn(
        name="get_id_from_muxed_address",
        module="a",
        export="5",
        arity=1,
        arg_names=("muxed_address",),
        arg_types=("MuxedAddressObject",),
        ret_type="U64Val",
        min_protocol=23,
        max_protocol=None,
        docs="Returns the multiplexing id corresponding to the provided MuxedAddressObject as a U64Val.",
    ),
    HostFn(
        name="get_address_executable",
        module="a",
        export="6",
        arity=1,
        arg_names=("address",),
        arg_types=("AddressObject",),
        ret_type="Val",
        min_protocol=23,
        max_protocol=None,
        docs="Returns the executable corresponding to the provided address. When the address does not exist on-chain, returns `Void` value. When it does exist, returns a value of `AddressExecutable` contract type. It is an enum with `Wasm` value and the corresponding Wasm hash for the Wasm contracts, `StellarAsset` value for Stellar Asset contract instances, and `Account` value for the 'classic' (G-) accounts.",
    ),
    HostFn(
        name="strkey_to_muxed_address",
        module="a",
        export="7",
        arity=1,
        arg_names=("strkey",),
        arg_types=("Val",),
        ret_type="Val",
        min_protocol=26,
        max_protocol=None,
        docs="Converts a provided Stellar strkey address of an account, muxed account, or a contract ('G...', 'M...' or 'C...' key respectively) to an AddressObject or MuxedAddressObject (for 'M...' keys). `strkey` can be either `BytesObject` or `StringObject` (the contents should represent the base32 strkey in both cases). Any other valid or invalid strkey (e.g. 'S...') will trigger an error. Prefer directly using the Address objects whenever possible. This is only useful in the context of custom messaging protocols (e.g. cross-chain).",
    ),
    HostFn(
        name="muxed_address_to_strkey",
        module="a",
        export="8",
        arity=1,
        arg_names=("address",),
        arg_types=("Val",),
        ret_type="StringObject",
        min_protocol=26,
        max_protocol=None,
        docs="Converts a provided AddressObject or MuxedAddressObject to Stellar strkey format ('G...' for account, 'M...' for muxed account, or 'C...' for contract). Prefer directly using the Address objects whenever possible. This is only useful in the context of custom messaging protocols (e.g. cross-chain).",
    ),
    HostFn(
        name="get_delegated_signers_for_current_auth_check",
        module="a",
        export="9",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="VecObject",
        min_protocol=27,
        max_protocol=None,
        docs="Returns a vector of `Address`es of all the delegated signers that have attached signatures to authorize the current account contract invocation. **Important**: These are user-provided inputs and should be treated accordingly, in a similar fashion to the actual signatures. Specifically, the account contract must ensure that these signers actually belong to it, and perform authentication for every one of them via `delegate_account_auth`. This may only be called within `__check_auth` contract function inside a custom account.",
    ),
    HostFn(
        name="delegate_account_auth",
        module="a",
        export="a",
        arity=1,
        arg_names=("address",),
        arg_types=("AddressObject",),
        ret_type="Void",
        min_protocol=27,
        max_protocol=None,
        docs="Delegates the custom account authentication to the provided address. This is only available when called within `__check_auth` contract function inside a custom account. This call will require the `address` to have authorized exactly the same call tree as the one being authorized by the current `__check_auth` call. Specifically, the same signature payload and the same context will be passed into `address`s authorization check. Panics if the call has not been authorized, or if called not from within `__check_auth`.",
    ),
    HostFn(
        name="dummy0",
        module="t",
        export="_",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="Val",
        min_protocol=None,
        max_protocol=None,
        docs="A dummy function taking 0 arguments and performs no-op. This function is for test purpose only, for measuring the roundtrip cost of invoking a host function, i.e. host->Vm->host.",
    ),
    HostFn(
        name="protocol_gated_dummy",
        module="t",
        export="0",
        arity=0,
        arg_names=(),
        arg_types=(),
        ret_type="Val",
        min_protocol=19,
        max_protocol=19,
        docs="A dummy function for testing the protocol gating. Takes 0 arguments and performs no-op. Essentially this function is always protocol-gated out since it has `min_supported_protocol == max_supported_protocol == 19`, thus having no effect on any protocol (Soroban starts at protocol 20). This is required for testing the scenario where ledger protocol version > host function max supported version, and the ledger protocol version must be <= the `env` version (which starts at 20, and is a compile-time, non-overridable constant).",
    ),
    HostFn(
        name="prng_reseed",
        module="p",
        export="_",
        arity=1,
        arg_names=("seed",),
        arg_types=("BytesObject",),
        ret_type="Void",
        min_protocol=None,
        max_protocol=None,
        docs="Reseed the frame-local PRNG with a given BytesObject, which should be 32 bytes long.",
    ),
    HostFn(
        name="prng_bytes_new",
        module="p",
        export="0",
        arity=1,
        arg_names=("length",),
        arg_types=("U32Val",),
        ret_type="BytesObject",
        min_protocol=None,
        max_protocol=None,
        docs="Construct a new BytesObject of the given length filled with bytes drawn from the frame-local PRNG.",
    ),
    HostFn(
        name="prng_u64_in_inclusive_range",
        module="p",
        export="1",
        arity=2,
        arg_names=("lo", "hi"),
        arg_types=("u64", "u64"),
        ret_type="u64",
        min_protocol=None,
        max_protocol=None,
        docs="Return a u64 uniformly sampled from the inclusive range [lo,hi] by the frame-local PRNG.",
    ),
    HostFn(
        name="prng_vec_shuffle",
        module="p",
        export="2",
        arity=1,
        arg_names=("vec",),
        arg_types=("VecObject",),
        ret_type="VecObject",
        min_protocol=None,
        max_protocol=None,
        docs="Return a (Fisher-Yates) shuffled clone of a given vector, using the frame-local PRNG.",
    ),
)
